/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 155
#define YY_END_OF_BUFFER 156
static yyconst short int yy_accept[635] =
    {   0,
        0,    0,    0,    0,    0,    0,  156,  155,  126,  155,
      105,  114,  104,  101,  102,  155,  103,  149,  149,  118,
      106,  119,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  116,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  115,  117,  123,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  111,  124,  110,
      128,  107,  129,  108,    0,  109,  153,  149,    0,    0,
        0,  112,  121,  120,  122,  113,  127,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   44,

        0,    0,    0,    0,    0,    0,   30,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   35,    0,   36,   46,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  125,    0,    0,    0,    0,
        0,    0,    0,    0,   94,    0,    0,    0,    0,    0,
        0,  130,  131,  153,  153,  153,  150,  151,  152,   43,
        0,    0,    0,    0,  140,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   33,   59,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   11,    0,
       47,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   75,    0,    0,    0,    0,
        0,    0,    0,    0,   53,    0,    0,   23,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  153,  154,  133,    0,
        0,    0,    0,    0,    0,  136,    0,   49,    0,   77,
      145,    0,    0,    0,   25,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   31,    4,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    8,    0,    0,   62,   63,

        0,   65,    0,   12,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   48,   76,
        0,    0,    0,    0,    0,    0,   52,    0,    0,   79,
        0,    0,    0,    0,    0,    0,    0,   86,    0,    0,
       92,    0,    0,    0,   97,    0,    0,    0,  154,  154,
      154,    0,    0,  146,  137,  138,  139,    0,    0,    0,
        0,    0,  141,    0,    0,   24,   26,    2,    0,    0,
        0,   29,    0,    0,    0,    0,    0,   45,    0,   58,
       34,    0,    0,   61,    9,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   74,    0,    0,    0,   50,    0,   39,    0,    0,
       41,   42,    0,    0,    0,    0,    0,    0,   87,   88,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  154,
        0,  148,    0,    0,  134,  142,  143,  144,    0,    0,
        0,    0,    0,    3,   56,    0,    0,    0,    0,    7,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   71,
        0,    0,   17,   37,    0,    0,   38,   19,   20,    0,
       40,   51,    0,    0,    0,    0,    0,   83,    0,   85,
       89,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      147,    0,    0,    0,    0,    0,   28,   57,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   69,    0,
       14,    0,    0,    0,    0,    0,   78,   80,    0,    0,
        0,    0,    0,    0,    0,   96,    0,    0,  100,    0,
       72,    0,    0,   27,    0,    0,    0,    0,   60,   10,
       64,    0,   13,   67,   68,    0,   16,   73,   18,    0,
        0,    0,    0,    0,    0,   91,   93,    0,   98,    0,
      135,    0,    0,    0,    0,    5,    0,    0,    0,    0,
       21,   22,   81,    0,   84,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   70,    0,    0,    0,    0,
        0,    0,    0,   55,   32,    6,   66,    0,    0,   90,

        0,    0,    0,    0,    0,    0,   82,   95,    0,    0,
        0,   54,    0,    0,    0,    1,    0,   99,    0,   15,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  132,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    1,    3,    1,    4,    5,    1,    1,
        1,    6,    7,    1,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   16,   18,   19,    1,    1,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
        1,    1,   30,    1,    1,   31,    1,    1,    1,   32,
        1,    1,   33,   34,   35,    1,    1,    1,    1,   36,
       37,    1,   38,   39,    1,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,    1,   65,    1,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1,    1,    5,    5,    5,    5,    6,    5,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        7,    5,    5,    6,    5,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[640] =
    {   0,
        0,    0,    0,    0,    0,    0,  750,  751,  728,   27,
      727,  742,  725,   61,   65,  736,  723,   65,   69,   59,
      722,   68,  719,  689,  687,  692,  685,  687,  684,  679,
       37,  671,  703,  695,  751,  674,  674,   43,   50,   35,
       51,   48,   57,   61,  670,   63,   61,   64,   80,   81,
       82,  676,  687,   88,  661,  751,  751,  665,  671,  666,
       91,   71,   99,  678,  673,   93,  680,  751,  751,  751,
      751,  751,  751,  751,  139,  751,  144,  149,  142,  162,
        0,  751,  751,  751,  751,  751,  751,  656,  665,  677,
      657,  662,  656,  660,  662,  655,  656,  657,  684,  650,

      662,   98,  665,  652,  135,  660,  751,  650,  644,  641,
      641,  648,  119,  641,  638,  655,  751,  640,  139,  751,
      629,  112,  634,  641,  638,   68,  645,  631,  137,  646,
      140,  640,  141,  634,   93,  148,  636,  627,  137,  628,
      628,  624,  639,  157,  628,  751,  637,  626,  622,  617,
      630,  616,  621,  618,  751,  629,  605,  615,  616,  606,
      608,  751,  751,  195,  196,  208,  206,  214,  654,  751,
      612,  605,  619,  619,  220,  600,  612,  608,  611,  596,
      645,  599,  611,  606,  607,  591,  161,  195,  595,  613,
      605,  600,  592,  598,  136,  597,  600,  751,  751,  583,

      585,  589,  588,  577,  575,  589,  569,  573,  751,  590,
      751,  192,  189,  581,  572,  569,  178,  566,  567,  574,
      579,  563,  195,  574,  575,  751,  575,  560,  558,  559,
      571,  556,  560,  568,  751,  567,  549,  751,  560,  552,
      557,  556,  557,  191,  557,  559,  554,  548,  556,  557,
      552,  565,  552,  551,  538,  541,  244,  253,  751,  552,
      541,  532,  572,  575,  572,  751,  533,  751,  533,  751,
      234,  548,  541,  533,  751,  534,  523,  531,  534,  518,
      520,  527,  530,  522,  751,  751,  520,  513,  526,  515,
      518,  524,  510,  509,  502,  751,  505,  506,  751,  751,

      503,  751,  501,  751,  519,  505,  501,  511,  511,  506,
      513,  499,  503,  510,  501,  492,  491,  488,  751,  751,
      497,  502,  501,  486,  499,  479,  751,  499,  486,  751,
      493,  492,  502,  484,  477,  481,  491,  482,  484,  472,
      243,  469,  482,  485,  751,  482,  481,  474,    0,    0,
      272,  479,  476,  501,  751,  751,  751,  476,  471,  499,
      502,  499,  751,  473,  464,  751,  751,  751,  459,  458,
      459,  751,  450,  449,  458,  448,  457,  751,  447,  751,
      751,  444,  457,  751,  751,  448,  451,  440,  439,  444,
      447,  446,  450,  430,  433,  448,  447,  430,  431,  433,

      433,  751,  442,  425,  426,  751,  434,  423,  429,  434,
      751,  751,  433,  436,  444,  422,  421,  427,  751,  751,
      444,  422,  429,  420,  436,  408,  407,  420,  411,  297,
      404,  751,  450,  407,  751,  751,  751,  751,  451,  418,
      398,  408,  397,  751,  751,  412,  405,  396,  403,  751,
      408,  409,  396,  407,  393,  405,  401,  381,  398,  751,
      397,  387,  751,  751,  395,  377,  751,  751,  751,  389,
      751,  751,  388,  392,  376,  392,  384,  751,  388,  751,
      751,  372,  371,  375,  379,  379,  372,  393,  377,  378,
      751,  371,  356,  361,  374,  373,  751,  751,  363,  362,

      354,  355,  362,  365,  352,  353,  358,  363,  751,  354,
      751,  355,  361,  346,  348,  361,  751,  751,  350,  341,
      348,  353,  349,  343,  336,  751,  337,  339,  751,  335,
      751,  379,  205,  751,  337,  336,  328,  346,  751,  751,
      751,  337,  751,  751,  751,  342,  751,  751,  751,  325,
      325,  337,  336,  335,  322,  751,  751,  333,  751,  334,
      751,  367,  331,  313,  330,  751,  325,  312,  317,  324,
      751,  751,  751,  311,  751,  326,  309,  324,  344,  304,
      313,  316,  312,  314,  311,  310,  315,  304,  313,  294,
      313,  287,  291,  751,  751,  751,  751,  292,  297,  751,

      296,  297,  335,  289,  279,  288,  751,  751,  286,  323,
      286,  751,  268,  274,  297,  751,  251,  751,  267,  751,
      279,  294,  265,  260,  291,  228,  265,  239,  214,  184,
      135,   62,  751,  751,  316,  321,  327,  330,  336
    } ;

static yyconst short int yy_def[640] =
    {   0,
      634,    1,  635,  635,  635,  635,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  636,  636,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  637,  634,  634,  634,
      638,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,

      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  637,  639,  634,  634,  638,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,

      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,

      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  258,  258,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,

      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,

      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,

      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,    0,  634,  634,  634,  634,  634
    } ;

static yyconst short int yy_nxt[818] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   19,   19,   19,   19,   19,   19,   19,   20,
       21,   22,   23,   24,   25,   26,   27,    8,   28,   29,
        8,   30,   31,   32,   33,    8,   34,    8,   35,   36,
       37,   38,   39,   40,   41,   42,    8,   43,    8,   44,
       45,   46,   47,   48,    8,   49,   50,   51,   52,   53,
       54,    8,    8,    8,   55,   56,   58,   71,   59,   60,
       61,   62,   73,   77,   63,   64,   65,   77,   82,   83,
       95,   72,  102,   66,  109,   74,  110,   67,   85,   86,
      112,  115,  103,  105,   96,  104,  111,  106,  113,  633,

      121,  117,  107,  114,  122,   79,  116,  118,  119,  634,
      124,  213,  108,  120,  126,  125,  128,   80,  153,  129,
      127,  634,  130,  131,  133,  214,   81,  132,  138,  154,
      634,  143,  228,  134,  144,  145,  159,  139,  135,  136,
      150,  137,  151,  155,  140,  160,  152,  162,  229,  156,
      164,  164,  167,  167,  184,  185,  208,  632,  163,   78,
       78,   78,   78,   78,   78,   78,   78,   78,  196,  209,
      197,  166,  168,  168,  168,  168,  168,  168,  168,  188,
      217,  202,  189,  203,  218,  288,  204,  166,  230,  219,
      225,  205,  289,  221,  222,  234,  206,  223,  226,  235,

      240,  231,  164,  164,  241,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  164,  164,  167,  167,  278,  309,
      279,  631,  310,  166,  168,  168,  168,  168,  168,  168,
      168,  263,  630,  264,  280,  302,  265,  266,  281,  166,
      304,  316,  303,  335,  305,  360,  629,  361,  563,  336,
      362,  363,  564,  317,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  421,  422,  423,  628,  350,  350,  350,  350,
      350,  350,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  627,  350,  350,  350,  350,  350,  350,  626,  625,

      624,  623,  622,  621,  620,  619,  351,  430,  430,  430,
      430,  430,  430,  430,  430,  430,    8,    8,    8,    8,
        8,    8,    8,   78,   78,  618,  617,   78,  165,  616,
      165,  615,  165,  169,  169,  169,  169,  257,  614,  257,
      613,  612,  611,  610,  609,  608,  607,  606,  605,  604,
      603,  602,  601,  600,  599,  598,  597,  596,  595,  594,
      593,  592,  591,  590,  589,  588,  587,  586,  585,  584,
      583,  582,  581,  580,  579,  578,  577,  576,  575,  574,
      573,  572,  571,  570,  569,  568,  567,  566,  565,  562,
      561,  560,  559,  558,  557,  556,  555,  554,  553,  552,

      551,  550,  549,  548,  547,  546,  545,  544,  543,  542,
      541,  540,  539,  538,  537,  536,  535,  534,  533,  532,
      531,  530,  529,  528,  527,  526,  525,  524,  523,  522,
      521,  520,  519,  518,  517,  516,  515,  514,  513,  512,
      511,  510,  509,  508,  507,  506,  505,  504,  503,  502,
      501,  500,  499,  498,  497,  496,  495,  494,  493,  492,
      491,  490,  489,  488,  487,  486,  485,  484,  483,  482,
      481,  480,  479,  478,  477,  476,  475,  474,  473,  472,
      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  456,  455,  454,  453,  452,

      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,
      431,  429,  428,  427,  426,  425,  424,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  359,  358,  357,  356,  355,  354,
      353,  352,  348,  347,  346,  345,  344,  343,  342,  341,

      340,  339,  338,  337,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  315,  314,  313,  312,  311,  308,  307,  306,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  287,  286,  285,  284,  283,  282,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  262,  261,
      260,  259,  258,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  239,  238,
      237,  236,  233,  232,  227,  224,  220,  216,  215,  212,
      211,  210,  207,  201,  200,  199,  198,  195,  194,  193,

      192,  191,  190,  187,  186,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  161,
      158,  157,  149,  148,  147,  146,  142,  141,  123,  101,
      100,   99,   98,   97,   94,   93,   92,   91,   90,   89,
       88,   87,   84,   76,   75,   70,   69,   68,   57,  634,
        7,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,

      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634
    } ;

static yyconst short int yy_chk[818] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   10,   14,   10,   10,
       10,   10,   15,   18,   10,   10,   10,   19,   20,   20,
       31,   14,   38,   10,   40,   15,   40,   10,   22,   22,
       41,   42,   38,   39,   31,   38,   40,   39,   41,  632,

       44,   43,   39,   41,   44,   18,   42,   43,   43,   19,
       46,  126,   39,   43,   47,   46,   48,   18,   62,   48,
       47,   19,   48,   49,   50,  126,   18,   49,   51,   62,
       19,   54,  135,   50,   54,   54,   66,   51,   50,   50,
       61,   50,   61,   63,   51,   66,   61,   75,  135,   63,
       77,   77,   79,   79,  102,  102,  122,  631,   75,   78,
       78,   78,   78,   78,   78,   78,   78,   78,  113,  122,
      113,   77,   80,   80,   80,   80,   80,   80,   80,  105,
      129,  119,  105,  119,  129,  195,  119,   77,  136,  129,
      133,  119,  195,  131,  131,  139,  119,  131,  133,  139,

      144,  136,  165,  165,  144,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  166,  166,  167,  167,  187,  217,
      187,  630,  217,  165,  168,  168,  168,  168,  168,  168,
      168,  175,  629,  175,  188,  212,  175,  175,  188,  165,
      213,  223,  212,  244,  213,  271,  628,  271,  533,  244,
      271,  271,  533,  223,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  341,  341,  341,  627,  258,  258,  258,  258,
      258,  258,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  626,  258,  258,  258,  258,  258,  258,  625,  624,

      623,  622,  621,  619,  617,  615,  258,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  635,  635,  635,  635,
      635,  635,  635,  636,  636,  614,  613,  636,  637,  611,
      637,  610,  637,  638,  638,  638,  638,  639,  609,  639,
      606,  605,  604,  603,  602,  601,  599,  598,  593,  592,
      591,  590,  589,  588,  587,  586,  585,  584,  583,  582,
      581,  580,  579,  578,  577,  576,  574,  570,  569,  568,
      567,  565,  564,  563,  562,  560,  558,  555,  554,  553,
      552,  551,  550,  546,  542,  538,  537,  536,  535,  532,
      530,  528,  527,  525,  524,  523,  522,  521,  520,  519,

      516,  515,  514,  513,  512,  510,  508,  507,  506,  505,
      504,  503,  502,  501,  500,  499,  496,  495,  494,  493,
      492,  490,  489,  488,  487,  486,  485,  484,  483,  482,
      479,  477,  476,  475,  474,  473,  470,  466,  465,  462,
      461,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      449,  448,  447,  446,  443,  442,  441,  440,  439,  434,
      433,  431,  429,  428,  427,  426,  425,  424,  423,  422,
      421,  418,  417,  416,  415,  414,  413,  410,  409,  408,
      407,  405,  404,  403,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,

      383,  382,  379,  377,  376,  375,  374,  373,  371,  370,
      369,  365,  364,  362,  361,  360,  359,  358,  354,  353,
      352,  348,  347,  346,  344,  343,  342,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  329,  328,  326,
      325,  324,  323,  322,  321,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  303,
      301,  298,  297,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  274,  273,  272,  269,  267,  265,  264,  263,  262,
      261,  260,  256,  255,  254,  253,  252,  251,  250,  249,

      248,  247,  246,  245,  243,  242,  241,  240,  239,  237,
      236,  234,  233,  232,  231,  230,  229,  228,  227,  225,
      224,  222,  221,  220,  219,  218,  216,  215,  214,  210,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  197,
      196,  194,  193,  192,  191,  190,  189,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  174,  173,
      172,  171,  169,  161,  160,  159,  158,  157,  156,  154,
      153,  152,  151,  150,  149,  148,  147,  145,  143,  142,
      141,  140,  138,  137,  134,  132,  130,  128,  127,  125,
      124,  123,  121,  118,  116,  115,  114,  112,  111,  110,

      109,  108,  106,  104,  103,  101,  100,   99,   98,   97,
       96,   95,   94,   93,   92,   91,   90,   89,   88,   67,
       65,   64,   60,   59,   58,   55,   53,   52,   45,   37,
       36,   34,   33,   32,   30,   29,   28,   27,   26,   25,
       24,   23,   21,   17,   16,   13,   12,   11,    9,    7,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,

      634,  634,  634,  634,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  634,  634
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#define STRING 1

#define CHAR 2

#line 14 "lex.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <ctype.h>
#line 21 "lex.l"
    char str[1024]; 
    void convertCharacterCodeToString(char charCode[], int pos, char *str);
#line 768 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 25 "lex.l"


#line 918 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 635 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 751 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "lex.l"
{printf("(%s) - ASSOCIATEDTYPE_KEY_WORD\n", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "lex.l"
{printf("(%s) - CLASS_KEY_WORD\n", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "lex.l"
{printf("(%s) - DEINIT_KEY_WORD\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "lex.l"
{printf("(%s) - ENUM_KEY_WORD\n", yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "lex.l"
{printf("(%s) - EXTENSION_KEY_WORD\n", yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "lex.l"
{printf("(%s) - FILEPRIVATE_KEY_WORD\n", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "lex.l"
{printf("(%s) - IMPORT_KEY_WORD\n", yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "lex.l"
{printf("(%s) - INIT_KEY_WORD\n", yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "lex.l"
{printf("(%s) - INOUT_KEY_WORD\n", yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "lex.l"
{printf("(%s) - INTERNAL_KEY_WORD\n", yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "lex.l"
{printf("(%s) - LET_KEY_WORD\n", yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "lex.l"
{printf("(%s) - OPEN_KEY_WORD\n", yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "lex.l"
{printf("(%s) - OPERATOR_KEY_WORD\n", yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "lex.l"
{printf("(%s) - PRIVATE_KEY_WORD\n", yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "lex.l"
{printf("(%s) - PRECEDENCEGROUP_KEY_WORD\n", yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "lex.l"
{printf("(%s) - PROTOCOL_KEY_WORD\n", yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "lex.l"
{printf("(%s) - PUBLIC_KEY_WORD\n", yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "lex.l"
{printf("(%s) - RETHROWS_KEY_WORD\n", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "lex.l"
{printf("(%s) - STATIC_KEY_WORD\n", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "lex.l"
{printf("(%s) - STRUCT_KEY_WORD\n", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "lex.l"
{printf("(%s) - SUBSCRIPT_KEY_WORD\n", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "lex.l"
{printf("(%s) - TYPEALIAS_KEY_WORD\n", yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "lex.l"
{printf("(%s) - VAR_KEY_WORD\n", yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "lex.l"
{printf("(%s) - BREAK_KEY_WORD\n", yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "lex.l"
{printf("(%s) - CASE_KEY_WORD\n", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "lex.l"
{printf("(%s) - CATCH_KEY_WORD\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "lex.l"
{printf("(%s) - CONTINUE_KEY_WORD\n", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "lex.l"
{printf("(%s) - DEFAULT_KEY_WORD\n", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "lex.l"
{printf("(%s) - DEFER_KEY_WORD\n", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "lex.l"
{printf("(%s) - DO_KEY_WORD\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "lex.l"
{printf("(%s) - ELSE_KEY_WORD\n", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "lex.l"
{printf("(%s) - FALLTHROUGH_KEY_WORD\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "lex.l"
{printf("(%s) - FOR_KEY_WORD\n", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "lex.l"
{printf("(%s) - GUARD_KEY_WORD\n", yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "lex.l"
{printf("(%s) - IF_KEY_WORD\n", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "lex.l"
{printf("(%s) - IN_KEY_WORD\n", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "lex.l"
{printf("(%s) - REPEAT_KEY_WORD\n", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "lex.l"
{printf("(%s) - RETURN_KEY_WORD\n", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "lex.l"
{printf("(%s) - THROW_KEY_WORD\n", yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "lex.l"
{printf("(%s) - SWITCH_KEY_WORD\n", yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "lex.l"
{printf("(%s) - WHERE_KEY_WORD\n", yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "lex.l"
{printf("(%s) - WHILE_KEY_WORD\n", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 72 "lex.l"
{printf("(%s) - ANY_KEY_WORD\n", yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 73 "lex.l"
{printf("(%s) - AS_KEY_WORD\n", yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 74 "lex.l"
{printf("(%s) - FALSE_KEY_WORD\n", yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 75 "lex.l"
{printf("(%s) - IS_KEY_WORD\n", yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 76 "lex.l"
{printf("(%s) - NIL_KEY_WORD\n", yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 77 "lex.l"
{printf("(%s) - SELF_KEY_WORD\n", yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 78 "lex.l"
{printf("(%s) - SELF_KEY_WORD\n", yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 79 "lex.l"
{printf("(%s) - SUPER_KEY_WORD\n", yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 80 "lex.l"
{printf("(%s) - THROWS_KEY_WORD\n", yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 81 "lex.l"
{printf("(%s) - TRUE_KEY_WORD\n", yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 82 "lex.l"
{printf("(%s) - TRY_KEY_WORD\n", yytext);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "lex.l"
{printf("(%s) - ASSOCIATIVITY_KEY_WORD\n", yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "lex.l"
{printf("(%s) - CONVENIENCE_KEY_WORD\n", yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "lex.l"
{printf("(%s) - DIDSET_KEY_WORD\n", yytext);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "lex.l"
{printf("(%s) - DYNAMIC_KEY_WORD\n", yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 89 "lex.l"
{printf("(%s) - FINAL_KEY_WORD\n", yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 90 "lex.l"
{printf("(%s) - GET_KEY_WORD\n", yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 91 "lex.l"
{printf("(%s) - INDIRECT_KEY_WORD\n", yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 92 "lex.l"
{printf("(%s) - INFIX_KEY_WORD\n", yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 93 "lex.l"
{printf("(%s) - LAZY_KEY_WORD\n", yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "lex.l"
{printf("(%s) - LEFT_KEY_WORD\n", yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "lex.l"
{printf("(%s) - MUTATING_KEY_WORD\n", yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 96 "lex.l"
{printf("(%s) - NONE_KEY_WORD\n", yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 97 "lex.l"
{printf("(%s) - NONMUTATING_KEY_WORD\n", yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "lex.l"
{printf("(%s) - OPTIONAL_KEY_WORD\n", yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 99 "lex.l"
{printf("(%s) - OVERRIDE_KEY_WORD\n", yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 100 "lex.l"
{printf("(%s) - POSTFIX_KEY_WORD\n", yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 101 "lex.l"
{printf("(%s) - PRECEDENCE_KEY_WORD\n", yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 102 "lex.l"
{printf("(%s) - PREFIX_KEY_WORD\n", yytext);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 103 "lex.l"
{printf("(%s) - PROTOCOL_KEY_WORD\n", yytext);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 104 "lex.l"
{printf("(%s) - REQUIRED_KEY_WORD\n", yytext);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 105 "lex.l"
{printf("(%s) - RIGHT_KEY_WORD\n", yytext);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 106 "lex.l"
{printf("(%s) - SET_KEY_WORD\n", yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 107 "lex.l"
{printf("(%s) - SOME_KEY_WORD\n", yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "lex.l"
{printf("(%s) - TYPE_KEY_WORD\n", yytext);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 109 "lex.l"
{printf("(%s) - UNOWNED_KEY_WORD\n", yytext);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 110 "lex.l"
{printf("(%s) - WEAK_KEY_WORD\n", yytext);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 111 "lex.l"
{printf("(%s) - WILLSET_KEY_WORD\n", yytext);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 114 "lex.l"
{printf("(%s) - #AVAILABLE_KEY_WORD\n", yytext);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 115 "lex.l"
{printf("(%s) - #COLORLITERAL_KEY_WORD\n", yytext);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 116 "lex.l"
{printf("(%s) - #COLUMN_KEY_WORD\n", yytext);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 117 "lex.l"
{printf("(%s) - #DSOHANDLE_KEY_WORD\n", yytext);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 118 "lex.l"
{printf("(%s) - #ELSEIF_WORD\n", yytext);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 119 "lex.l"
{printf("(%s) - #ELSE_WORD\n", yytext);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 120 "lex.l"
{printf("(%s) - #ENDIF_KEY_WORD\n", yytext);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 121 "lex.l"
{printf("(%s) - #ERROR_KEY_WORD\n", yytext);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 122 "lex.l"
{printf("(%s) - #FILEID_KEY_WORD\n", yytext);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 123 "lex.l"
{printf("(%s) - #FILELITERAL_KEY_WORD\n", yytext);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 124 "lex.l"
{printf("(%s) - #FILEPATH_KEY_WORD\n", yytext);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 125 "lex.l"
{printf("(%s) - #FILE_KEY_WORD\n", yytext);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 126 "lex.l"
{printf("(%s) - #FUNCTION_KEY_WORD\n", yytext);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 127 "lex.l"
{printf("(%s) - #IF_WORD\n", yytext);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 128 "lex.l"
{printf("(%s) - #IMAGELITERAL_KEY_WORD\n", yytext);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 129 "lex.l"
{printf("(%s) - #KEYPATH_KEY_WORD\n", yytext);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 130 "lex.l"
{printf("(%s) - #LINE_KEY_WORD\n", yytext);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 131 "lex.l"
{printf("(%s) - #SELECTOR_KEY_WORD\n", yytext);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 132 "lex.l"
{printf("(%s) - #SOURCELOCATION_KEY_WORD\n", yytext);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 133 "lex.l"
{printf("(%s) - #WARNING_KEY_WORD\n", yytext);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 136 "lex.l"
{ printf("Found OPERATOR_PLUS: $s\n", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 137 "lex.l"
{ printf("Found OPERATOR_MINUS: $s\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 138 "lex.l"
{ printf("Found OPERATOR_DIVISION: $s\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 139 "lex.l"
{ printf("Found OPERATOR_MULTIPLICATION: %s\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 140 "lex.l"
{ printf("Found OPERATOR_MODULUS: %s\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 143 "lex.l"
{ printf("Found OPERATOR_ASSIGNMENT: $s\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 144 "lex.l"
{ printf("Found OPERATOR_PLUS_ASSIGNMENT: $s\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 145 "lex.l"
{ printf("Found OPERATOR_MINUS_ASSIGNMENT: $s\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 146 "lex.l"
{ printf("Found OPERATOR_DIVIDE_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 147 "lex.l"
{ printf("Found OPERATOR_MUTIPLY_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 148 "lex.l"
{ printf("Found OPERATOR_MODULUS_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 151 "lex.l"
{ printf("Found OPERATOR_LEFT_SHIFT: $s\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 152 "lex.l"
{ printf("Found OPERATOR_RIGHT_SHIFT: $s\n", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 153 "lex.l"
{ printf("Found OPERATOR_BINARY_AND: $s\n", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 154 "lex.l"
{ printf("Found OPERATOR_BINARY_OR: %s\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 155 "lex.l"
{ printf("Found OPERATOR_BINARY_XOR: %s\n", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 156 "lex.l"
{ printf("Found OPERATOR_TILDE: %s\n", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 159 "lex.l"
{ printf("Found OPERATOR_LESS: $s\n", yytext); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 160 "lex.l"
{ printf("Found OPERATOR_GREATER: $s\n", yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 161 "lex.l"
{ printf("Found OPERATOR_EQUAL: $s\n", yytext); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 162 "lex.l"
{ printf("Found OPERATOR_LESS_OR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 163 "lex.l"
{ printf("Found OPERATOR_GREATER_OR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 164 "lex.l"
{ printf("Found OPERATOR_NOT_EQUAL: %s\n", yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 167 "lex.l"
{ printf("Found OPERATOR_LOGICAL_AND: $s\n", yytext); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 168 "lex.l"
{ printf("Found OPERATOR_LOGICAL_OR: $s\n", yytext); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 169 "lex.l"
{ printf("Found OPERATOR_LOGICAL_NOT: $s\n", yytext); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 172 "lex.l"
{ printf("Found OPERATOR_NIL_COALESCING: $s\n", yytext); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 173 "lex.l"
{ printf("Found OPERATOR_INCREMENT: $s\n", yytext); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 174 "lex.l"
{ printf("Found OPERATOR_DECREMENT: $s\n", yytext); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 177 "lex.l"
{ printf("Found OPERATOR_CLOSED_RANGE: $s\n", yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 178 "lex.l"
{ printf("Found OPERATOR_HALF_OPEN_RANGE: $s\n", yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 179 "lex.l"
{ printf("Found OPERATOR_ONE_SIDED_RANGE: $s\n", yytext); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 181 "lex.l"
{ printf("Found TYPE_BOOL: %s\n", yytext); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 182 "lex.l"
{ printf("Found TYPE_STRING: %s\n", yytext); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 183 "lex.l"
{ printf("Found TYPE_CHARACTER: %s\n", yytext); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 184 "lex.l"
{ printf("Found TYPE_INT8: %s\n", yytext); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 185 "lex.l"
{ printf("Found TYPE_INT16: %s\n", yytext); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 186 "lex.l"
{ printf("Found TYPE_INT32: %s\n", yytext); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 187 "lex.l"
{ printf("Found TYPE_INT64: %s\n", yytext); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 188 "lex.l"
{ printf("Found TYPE_INT: %s\n", yytext); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 189 "lex.l"
{ printf("Found TYPE_UINT8: %s\n", yytext); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 190 "lex.l"
{ printf("Found TYPE_UINT16: %s\n", yytext); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 191 "lex.l"
{ printf("Found TYPE_UINT32: %s\n", yytext); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 192 "lex.l"
{ printf("Found TYPE_UINT64: %s\n", yytext); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 193 "lex.l"
{ printf("Found TYPE_UINT: %s\n", yytext); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 194 "lex.l"
{ printf("Found TYPE_FLOAT: %s\n", yytext); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 195 "lex.l"
{ printf("Found TYPE_FLOAT80: %s\n", yytext); }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 196 "lex.l"
{ printf("Found TYPE_DOUBLE: %s\n", yytext); }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 200 "lex.l"
{
    printf("DECIMAL_NUMBER: %d\n", atoi(str));
}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 204 "lex.l"
{

    if(strlen(str) > 2)
    {
         printf("BIN_NUMBER: %d\n", strtol(str + 2, NULL, 2));
    }
    else
    {
       printf("Error: incorrect format for DECIMAL_NUMBER\n");
    }
}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 216 "lex.l"
{

    if(strlen(str) > 2)
    {
         printf("OCTAL_NUMBER: %d\n", strtol(str + 2, NULL, 2));
    }
    else
    {
        printf("Error: incorrect format for OCTAL_NUMBER\n");
    }
}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 228 "lex.l"
{

    if(strlen(str) > 2)
    {
        printf("HEXADEMICAL_NUMBER: %d\n", strtol(str + 2, NULL, 2));
    }
    else
    {
        printf("Error: incorrect format for HEXADEMICAL_NUMBER\n");
    }
}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 240 "lex.l"
{

    printf("DECIMAL_FLOATINGPOINT_NUMBER: %f\n", atof(str), str);
}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 245 "lex.l"
{

    printf("HEXADECIMAL_FLOATINGPOINT_NUMBER: %f\n", atof(str), str);
}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 251 "lex.l"
ECHO;
	YY_BREAK
#line 1814 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 635 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 635 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 634);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 251 "lex.l"


void convertCharacterCodeToString(char charCode[], int pos, char *str)
{
    str[0] = strtol(charCode + pos, NULL, 16);
    str[1] = '\0';
}

int main( int argc, char** argv)
{
    if (argc == 2)
    {
        FILE *file = fopen(argv[1], "r");
        if (file == NULL) 
        {
            printf("File opening error");
            return 1;
        }
        yyin = file;
        yylex();
        fclose(file);
        return 0;
    }
    else
    {
        printf("missed commandline argument");
        return 1;
    }
}